### PR TITLE
Fix: 'MongodumpThread' object has no attribute 'client_cert_file'

### PR DESCRIPTION
**Pull request by carl-peng**
Fix wrong ssl flag to avoid always fail in 'object has no attribute 'client_cert_file' when try connect to an MongoDB with SSL

### CODE REVIEW

**Comment by timvaillancourt** [comment]
Blocked by #238. This will fix the Travis CI failure blocking this PR

**Comment by timvaillancourt** [comment]
Hi @carl-peng,

Unfortunately a new flake8 code quality check is blocking your change. I've fixed this new flake8 error in #238, however this means you'll need to merge master into your branch to get this fix. Could you do that please?

This can be done in your branch's checkout with:
1. git remote add upstream https://github.com/Percona-Lab/mongodb_consistent_backup
2. git fetch upstream
3. git merge upstream/master
4. git push

Thanks!

Tim

**Comment by carl-peng** [comment]
hi, Tim,
Sure, I'll do it.
Thanks a lot for notice.

Carl

**Comment by timvaillancourt** [comment]
This looks good now, thanks @carl-peng!

**Pull request merged**
