### PR TITLE
Dockerize app

### PR DESCRIPTION
**Pull request by TimJones**
Adds a Dockerfile for publishing a Docker container of the application.

### CODE REVIEW

**Comment by TimJones** [comment]
It is simply to have a containerised deployment of the app, as I would like to launch this as a job from our Kubernetes cluster.

The backup location can be mapped to an external volume with lots of space at run-time.

**Comment by fruitl00p** [comment]
@TimJones I was looking into this as well. @dbmurphy This allows the backups to be created with a single command accross nodes that might not have the full mongo (already) there (aside from the kubernetes / mesos) usage... 

I threw this (https://github.com/fruitl00p/mongodb_consistent_backup-docker) together to achieve the same thing ;)

**Comment by TimJones** [comment]
Forgot to add: configuration is provided by command-line parameters, or by mapping an external configuration file into the container.

**Comment by timvaillancourt** [comment]
Funny enough, I also made a Dockerfile last night for this project. LGTM

**Comment by timvaillancourt** [comment]
You can see my Dockerfile here: https://github.com/timvaillancourt/mongodb_consistent_backup/tree/dockerfile_v1/Dockerfile.

It's a bit simpler because it relies on the project being built outside of the image with "make docker" (added to Makefile).

**Comment by TimJones** [comment]
@timvaillancourt How does the mongo_consistent_backup script call mongodump, I couldn't find it in your container?

**Comment by timvaillancourt** [comment]
Good catch @TimJones, it looks like I didn't commit my change to install mongodump! I'll add that so we can compare which approach is best.

**Comment by timvaillancourt** [comment]
I've realised I've made a poor assumption in my Dockerfile: while pex does build binaries with all python dependencies contained, some of those dependencies have linkages to C-based libraries on the host.

This means that copying the binary into the Docker image is a bad idea as it could build on a different OS than what is inside the Docker, causing C-level linkages to libraries that may be different.

This means we should build the whole project in Docker, like @TimJones did to begin with.

**Pull request closed without merging**
